# Generated by Django 3.2.16 on 2022-11-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtisite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='simp_id',
            field=models.IntegerField(default=0, verbose_name='SIMP id'),
            preserve_default=False,
        ),
    ]
