# Generated by Django 3.2.16 on 2022-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtisite', '0002_auto_20221109_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Region name')),
                ('simp_id', models.IntegerField(verbose_name='SIMP id')),
            ],
        ),
    ]
