# Generated by Django 3.2.16 on 2022-11-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jtisite', '0003_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='jtisite.region', verbose_name='Region'),
            preserve_default=False,
        ),
    ]
